### ISSUE TITLE
`VelloFont` is `Arc<Arc<[u8]>>`

### ISSUE THREAD

**Issue by BD103** [linebender/bevy_vello#60]
The `VelloFont` asset can be simplified down to `Arc<Arc<[u8]>>`. It's generally bad practice to wrap an `Arc` in another `Arc` because it requires two pointer dereferences on every access, which can hurt caching.

```rust
pub struct VelloFont {
    pub font: Arc<peniko::Font>,
}

pub struct peniko::Font {
    pub data: Blob<u8>,
    pub index: u32,
}

pub struct Blob<T> {
    data: Arc<dyn AsRef<[T]>>,
    id: u64,
}

// Or in other words
pub struct VelloFont {
    pub font: Arc<peniko::Font>,
}

pub struct VelloFont {
    pub font: Arc<Blob<u8>>,
}

pub struct VelloFont {
    pub font: Arc<Arc<dyn AsRef<[u8]>>>,
}
```

I propose `VelloFont` no longer wraps `peniko::Font` in an `Arc` and depends on `Font` to keep it shareable.

**Comment by BD103** [comment]
Removing the `Arc` will increase the size of `VelloFont` from 8 bytes to 32 bytes on a 64-bit computer, but the performance gains from removing the extra pointer abstraction may be worth it. This probably needs testing :)

**Comment by dannymcgee** [comment]
It's actually `Arc<Arc<Arc<...>>>` once it's loaded into the engine, because Bevy's `Handle` is _also_ an `Arc` wrapper. :P

**Comment by simbleau** [comment]
I don't think this is a valid issue. For one, I have no control over what a `peniko::Font` is, because that comes from a different crate. Secondly, if I start to subsume the data it has, I'm replacing and maintaining it.

I think `Arc<Arc<T>>` is totally fine in this case. It's a trade of design over performance.

**Comment by DJMcNab** [comment]
I'm confused by this response, because `peniko::Font` [is Clone](https://docs.rs/peniko/latest/peniko/struct.Font.html#impl-Clone-for-Font). What other property of the font being an `Arc` are you using?

**Comment by BD103** [comment]
I think the concern is more what if `peniko::Font` changes its internal representation to no longer be an `Arc`, though a clarification would be nice.

**Comment by simbleau** [comment]
> I'm confused by this response, because `peniko::Font` [is Clone](https://docs.rs/peniko/latest/peniko/struct.Font.html#impl-Clone-for-Font). What other property of the font being an `Arc` are you using?

The original poster was saying that a `peniko::Font` uses Arc to store data. See "Blob".

```
pub struct peniko::Font {
    pub data: Blob<u8>,
    pub index: u32,
}

pub struct Blob<T> {
    data: Arc<dyn AsRef<[T]>>,
    id: u64,
}
```

In bevy_vello, we store a `VelloFont` as newtype of `Arc<peniko::Font>`.

My interpretation is that the original post didn't make much sense, because the suggestion was to change VelloFont to this:

```rust
pub struct VelloFont {
    pub font: Arc<[u8]>,
}
```

Which ignored all of the other data fields (index, id, etc.) necessary to store font data. And at that point if I had to re-add them back, we'd be making maintaining our own font definition, which I don't agree with or like at all.

**Comment by BD103** [comment]
Oh, my apologies! What I meant to say was that `VelloFont` should be changed to this:

```rust
pub struct VelloFont {
    pub font: peniko::Font,
}
```

`peniko` can absolutely still be used here, I didn't mean to suggest that it should be removed.

**Comment by simbleau** [comment]
Ah, that makes a lot more sense now.

**Comment by simbleau** [comment]
This was put into #61 with co-author credit @BD103 . Thanks again!

**Comment by BD103** [comment]
Sounds great, I'm glad we could get it figured out!
